const dashboardStyles = {
  page: {
    padding: '40px 60px',
    minHeight: '100vh',
    background: 'linear-gradient(180deg, #eff6ff 0%, #f0f9ff 100%)',
    fontFamily: "'Inter', 'Segoe UI', -apple-system, BlinkMacSystemFont, sans-serif",
    color: '#1e3a8a',
  },
  container: {
    maxWidth: '1000px',
    margin: '0 auto',
    backgroundColor: '#ffffff',
    borderRadius: '16px',
    padding: '40px 50px',
    boxShadow: '0 8px 30px rgba(59, 130, 246, 0.15)',
    border: '2px solid #dbeafe',
  },
  heading: {
    fontSize: '2.5rem',
    fontWeight: '800',
    marginBottom: '24px',
    background: 'linear-gradient(135deg, #1e40af 0%, #3b82f6 100%)',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
    letterSpacing: '-0.5px',
  },
  subheading: {
    fontSize: '1.4rem',
    marginBottom: '20px',
    color: '#475569',
    fontWeight: '600',
  },
  button: {
    background: 'linear-gradient(135deg, #3b82f6 0%, #1d4ed8 100%)',
    border: 'none',
    padding: '14px 28px',
    borderRadius: '10px',
    color: '#fff',
    cursor: 'pointer',
    fontWeight: '600',
    fontSize: '1rem',
    transition: 'all 0.3s ease',
    boxShadow: '0 4px 15px rgba(59, 130, 246, 0.4)',
    letterSpacing: '0.3px',
  },
  buttonHover: {
    background: 'linear-gradient(135deg, #2563eb 0%, #1e40af 100%)',
    boxShadow: '0 6px 20px rgba(59, 130, 246, 0.6)',
    transform: 'translateY(-2px)',
  },
  input: {
    width: '100%',
    padding: '12px 16px',
    marginBottom: '18px',
    borderRadius: '10px',
    border: '2px solid #dbeafe',
    fontSize: '1rem',
    background: '#f0f9ff',
    transition: 'all 0.3s ease',
    outline: 'none',
    boxSizing: 'border-box',
    color: '#1e3a8a',
  },
  inputFocus: {
    border: '2px solid #3b82f6',
    background: '#ffffff',
    boxShadow: '0 0 0 4px rgba(59, 130, 246, 0.1)',
  },
  label: {
    fontWeight: '600',
    marginBottom: '8px',
    display: 'block',
    color: '#475569',
    fontSize: '0.95rem',
    letterSpacing: '0.2px',
  },
  logoutButton: {
    background: '#ef4444',
    border: 'none',
    padding: '12px 24px',
    borderRadius: '8px',
    color: '#fff',
    cursor: 'pointer',
    fontWeight: '600',
    float: 'right',
    transition: 'all 0.2s ease',
    boxShadow: '0 1px 3px rgba(239, 68, 68, 0.3)',
  },
  logoutButtonHover: {
    background: '#dc2626',
    boxShadow: '0 2px 5px rgba(239, 68, 68, 0.4)',
  },
  appointmentList: {
    listStyleType: 'none',
    padding: 0,
    marginTop: '24px',
  },
  appointmentItem: {
    background: 'linear-gradient(135deg, #ffffff 0%, #f0f9ff 100%)',
    marginBottom: '16px',
    padding: '24px',
    borderRadius: '12px',
    border: '2px solid #dbeafe',
    transition: 'all 0.3s ease',
  },
  appointmentItemHover: {
    boxShadow: '0 6px 20px rgba(59, 130, 246, 0.2)',
    borderColor: '#3b82f6',
    transform: 'translateY(-2px)',
  },
  notification: {
    color: '#f59e0b',
    fontWeight: '600',
    marginTop: '8px',
    padding: '8px 16px',
    background: '#fffbeb',
    borderRadius: '8px',
    display: 'inline-block',
    fontSize: '0.9rem',
    border: '1px solid #fef3c7',
  },
  section: {
    marginTop: '40px',
    padding: '32px',
    background: 'linear-gradient(135deg, #f0f9ff 0%, #e0f2fe 100%)',
    borderRadius: '12px',
    border: '2px solid #bfdbfe',
  },
};

export default dashboardStyles;
