const doctorDashboardStyles = {
  page: {
    padding: '40px 60px',
    minHeight: '100vh',
    background: 'linear-gradient(180deg, #eff6ff 0%, #f0f9ff 100%)',
    fontFamily: "'Inter', 'Segoe UI', -apple-system, BlinkMacSystemFont, sans-serif",
    color: '#1e3a8a',
  },
  container: {
    maxWidth: '1200px',
    margin: '0 auto',
    backgroundColor: '#ffffff',
    borderRadius: '16px',
    padding: '40px 50px',
    boxShadow: '0 8px 30px rgba(59, 130, 246, 0.15)',
    border: '2px solid #dbeafe',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '40px',
    paddingBottom: '24px',
    borderBottom: '3px solid #bfdbfe',
  },
  heading: {
    fontSize: '2.5rem',
    fontWeight: '800',
    background: 'linear-gradient(135deg, #1e40af 0%, #3b82f6 100%)',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
    letterSpacing: '-0.5px',
    margin: 0,
  },
  logoutButton: {
    background: '#ef4444',
    border: 'none',
    padding: '12px 24px',
    borderRadius: '8px',
    color: '#fff',
    cursor: 'pointer',
    fontWeight: '600',
    transition: 'all 0.2s ease',
    boxShadow: '0 1px 3px rgba(239, 68, 68, 0.3)',
    fontSize: '1rem',
  },
  logoutButtonHover: {
    background: '#dc2626',
    boxShadow: '0 2px 5px rgba(239, 68, 68, 0.4)',
  },
  section: {
    marginTop: '40px',
    padding: '32px',
    background: 'linear-gradient(135deg, #f0f9ff 0%, #e0f2fe 100%)',
    borderRadius: '12px',
    border: '2px solid #bfdbfe',
  },
  sectionTitle: {
    fontSize: '1.6rem',
    fontWeight: '700',
    marginBottom: '24px',
    color: '#1e40af',
    letterSpacing: '-0.3px',
  },
  appointmentList: {
    listStyleType: 'none',
    padding: 0,
    margin: 0,
  },
  appointmentCard: {
    background: 'linear-gradient(135deg, #ffffff 0%, #f0f9ff 100%)',
    marginBottom: '20px',
    padding: '24px',
    borderRadius: '12px',
    border: '2px solid #dbeafe',
    transition: 'all 0.3s ease',
    boxShadow: '0 4px 15px rgba(59, 130, 246, 0.1)',
  },
  appointmentCardHover: {
    boxShadow: '0 8px 25px rgba(59, 130, 246, 0.25)',
    borderColor: '#3b82f6',
    transform: 'translateY(-3px)',
  },
  appointmentInfo: {
    marginBottom: '12px',
    fontSize: '1rem',
    color: '#475569',
    lineHeight: '1.6',
  },
  appointmentLabel: {
    fontWeight: '600',
    color: '#1e293b',
    display: 'inline-block',
    minWidth: '120px',
  },
  button: {
    background: 'linear-gradient(135deg, #3b82f6 0%, #1d4ed8 100%)',
    border: 'none',
    padding: '12px 24px',
    borderRadius: '10px',
    color: '#fff',
    cursor: 'pointer',
    fontWeight: '600',
    fontSize: '1rem',
    transition: 'all 0.3s ease',
    boxShadow: '0 4px 15px rgba(59, 130, 246, 0.4)',
    marginRight: '12px',
    letterSpacing: '0.3px',
  },
  buttonHover: {
    background: 'linear-gradient(135deg, #2563eb 0%, #1e40af 100%)',
    boxShadow: '0 6px 20px rgba(59, 130, 246, 0.6)',
    transform: 'translateY(-2px)',
  },
  cancelButton: {
    background: '#ef4444',
    border: 'none',
    padding: '12px 24px',
    borderRadius: '8px',
    color: '#fff',
    cursor: 'pointer',
    fontWeight: '600',
    fontSize: '1rem',
    transition: 'all 0.2s ease',
    boxShadow: '0 1px 3px rgba(239, 68, 68, 0.3)',
    letterSpacing: '0.3px',
  },
  cancelButtonHover: {
    background: '#dc2626',
    boxShadow: '0 2px 5px rgba(239, 68, 68, 0.4)',
  },
  input: {
    width: '100%',
    padding: '12px 16px',
    marginBottom: '18px',
    borderRadius: '10px',
    border: '2px solid #dbeafe',
    fontSize: '1rem',
    background: '#f0f9ff',
    transition: 'all 0.3s ease',
    outline: 'none',
    boxSizing: 'border-box',
    color: '#1e3a8a',
  },
  inputFocus: {
    border: '2px solid #3b82f6',
    background: '#ffffff',
    boxShadow: '0 0 0 4px rgba(59, 130, 246, 0.1)',
  },
  select: {
    width: '100%',
    padding: '12px 16px',
    marginBottom: '18px',
    borderRadius: '8px',
    border: '2px solid #e2e8f0',
    fontSize: '1rem',
    background: '#f8fafc',
    transition: 'all 0.2s ease',
    outline: 'none',
    boxSizing: 'border-box',
    color: '#1e293b',
    cursor: 'pointer',
  },
  selectFocus: {
    border: '2px solid #2563eb',
    background: '#ffffff',
  },
  label: {
    fontWeight: '600',
    marginBottom: '8px',
    display: 'block',
    color: '#475569',
    fontSize: '0.95rem',
    letterSpacing: '0.2px',
  },
  formSection: {
    marginTop: '32px',
    padding: '28px',
    background: '#ffffff',
    borderRadius: '12px',
    border: '1px solid #e2e8f0',
  },
  formTitle: {
    fontSize: '1.3rem',
    fontWeight: '700',
    marginBottom: '20px',
    color: '#1e293b',
  },
  statusBadge: {
    display: 'inline-block',
    padding: '6px 16px',
    borderRadius: '20px',
    fontSize: '0.85rem',
    fontWeight: '600',
    marginLeft: '12px',
    letterSpacing: '0.3px',
  },
  statusPending: {
    background: '#fef3c7',
    color: '#92400e',
    border: '1px solid #fde68a',
  },
  statusConfirmed: {
    background: '#d1fae5',
    color: '#065f46',
    border: '1px solid #a7f3d0',
  },
  statusCompleted: {
    background: 'linear-gradient(135deg, #dbeafe 0%, #bfdbfe 100%)',
    color: '#1e40af',
    border: '2px solid #93c5fd',
  },
  statusCancelled: {
    background: '#fee2e2',
    color: '#991b1b',
    border: '1px solid #fecaca',
  },
  emptyState: {
    textAlign: 'center',
    padding: '60px 24px',
    color: '#64748b',
    fontSize: '1.1rem',
    fontStyle: 'italic',
  },
};

export default doctorDashboardStyles;
