const patientDashboardStyles = {
  page: {
    padding: '0',
    minHeight: '100vh',
    background: 'linear-gradient(135deg, #e0f2fe 0%, #dbeafe 100%)',
    fontFamily: "'Inter', 'Segoe UI', -apple-system, BlinkMacSystemFont, sans-serif",
    color: '#1e3a8a',
  },
  container: {
    minHeight: '100vh',
    padding: '0',
  },
  
  // New Welcome Hero Section
  welcomeHero: {
    background: 'linear-gradient(135deg, #1e40af 0%, #3b82f6 100%)',
    padding: '60px 40px',
    color: 'white',
    position: 'relative',
    overflow: 'hidden',
  },
  welcomeContent: {
    maxWidth: '1200px',
    margin: '0 auto',
    position: 'relative',
    zIndex: 1,
  },
  welcomePattern: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    opacity: 0.1,
    backgroundImage: 'radial-gradient(circle at 20px 20px, white 2px, transparent 0)',
    backgroundSize: '40px 40px',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '30px',
  },
  welcomeText: {
    fontSize: '2.5rem',
    fontWeight: '800',
    margin: 0,
    textShadow: '0 2px 10px rgba(0, 0, 0, 0.2)',
  },
  welcomeSubtext: {
    fontSize: '1.1rem',
    marginTop: '10px',
    opacity: 0.95,
  },
  
  // Stats Cards Section
  statsSection: {
    maxWidth: '1200px',
    margin: '-40px auto 0',
    padding: '0 40px',
    position: 'relative',
    zIndex: 10,
  },
  statsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(250px, 1fr))',
    gap: '24px',
    marginBottom: '40px',
  },
  statCard: {
    background: 'white',
    borderRadius: '16px',
    padding: '28px',
    boxShadow: '0 10px 30px rgba(0, 0, 0, 0.15)',
    transition: 'all 0.3s ease',
    border: '1px solid rgba(59, 130, 246, 0.1)',
    cursor: 'pointer',
  },
  statCardHover: {
    transform: 'translateY(-8px)',
    boxShadow: '0 15px 40px rgba(59, 130, 246, 0.25)',
  },
  statIcon: {
    width: '50px',
    height: '50px',
    borderRadius: '12px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '24px',
    marginBottom: '16px',
    background: 'linear-gradient(135deg, #dbeafe 0%, #bfdbfe 100%)',
  },
  statValue: {
    fontSize: '2.5rem',
    fontWeight: '800',
    background: 'linear-gradient(135deg, #1e40af 0%, #3b82f6 100%)',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
    marginBottom: '8px',
  },
  statLabel: {
    fontSize: '0.95rem',
    color: '#64748b',
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: '0.5px',
  },
  
  // Main Content Area
  mainContent: {
    maxWidth: '1200px',
    margin: '0 auto',
    padding: '40px',
    background: '#f8fafc',
    minHeight: 'calc(100vh - 300px)',
  },
  heading: {
    fontSize: '2.5rem',
    fontWeight: '800',
    background: 'linear-gradient(135deg, #1e40af 0%, #3b82f6 100%)',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
    letterSpacing: '-0.5px',
    margin: 0,
  },
  logoutButton: {
    background: '#ef4444',
    border: 'none',
    padding: '12px 24px',
    borderRadius: '8px',
    color: '#fff',
    cursor: 'pointer',
    fontWeight: '600',
    transition: 'all 0.2s ease',
    boxShadow: '0 1px 3px rgba(239, 68, 68, 0.3)',
    fontSize: '1rem',
  },
  logoutButtonHover: {
    background: '#dc2626',
    boxShadow: '0 2px 5px rgba(239, 68, 68, 0.4)',
  },
  section: {
    marginTop: '40px',
    padding: '32px',
    background: 'linear-gradient(135deg, #f0f9ff 0%, #e0f2fe 100%)',
    borderRadius: '12px',
    border: '2px solid #bfdbfe',
  },
  sectionTitle: {
    fontSize: '2rem',
    fontWeight: '800',
    marginBottom: '30px',
    background: 'linear-gradient(135deg, #1e40af 0%, #3b82f6 100%)',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
    letterSpacing: '-0.5px',
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  
  // New Appointment Button
  newAppointmentButton: {
    background: 'linear-gradient(135deg, #10b981 0%, #059669 100%)',
    border: 'none',
    padding: '16px 32px',
    borderRadius: '12px',
    color: 'white',
    fontSize: '1.1rem',
    fontWeight: '700',
    cursor: 'pointer',
    transition: 'all 0.3s ease',
    boxShadow: '0 4px 15px rgba(16, 185, 129, 0.4)',
    marginBottom: '32px',
    display: 'inline-flex',
    alignItems: 'center',
    gap: '10px',
    letterSpacing: '0.3px',
  },
  
  // Appointments List
  appointmentsList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '20px',
  },
  appointmentListItem: {
    background: 'white',
    borderRadius: '16px',
    overflow: 'hidden',
    boxShadow: '0 4px 15px rgba(0, 0, 0, 0.1)',
    transition: 'all 0.3s ease',
    border: '2px solid #e0f2fe',
    backdropFilter: 'blur(10px)',
    cursor: 'pointer',
  },
  appointmentHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '24px',
    cursor: 'pointer',
    background: 'white',
  },
  appointmentMainInfo: {
    display: 'flex',
    alignItems: 'center',
    gap: '20px',
    flex: 1,
  },
  appointmentDateBadge: {
    width: '70px',
    height: '70px',
    borderRadius: '12px',
    background: 'linear-gradient(135deg, #3b82f6 0%, #1d4ed8 100%)',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    color: 'white',
    boxShadow: '0 4px 15px rgba(59, 130, 246, 0.3)',
  },
  dateDay: {
    fontSize: '2rem',
    fontWeight: '800',
    lineHeight: '1',
  },
  dateMonth: {
    fontSize: '0.85rem',
    fontWeight: '600',
    textTransform: 'uppercase',
    marginTop: '4px',
    opacity: 0.9,
  },
  appointmentSummary: {
    flex: 1,
  },
  doctorName: {
    fontSize: '1.3rem',
    fontWeight: '700',
    color: '#1e293b',
    marginBottom: '6px',
  },
  appointmentTime: {
    fontSize: '1rem',
    color: '#64748b',
    fontWeight: '500',
  },
  appointmentYear: {
    fontSize: '0.85rem',
    color: '#94a3b8',
    marginTop: '4px',
  },
  appointmentActions: {
    display: 'flex',
    alignItems: 'center',
    gap: '16px',
  },
  expandButton: {
    width: '40px',
    height: '40px',
    borderRadius: '10px',
    background: '#f0f9ff',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    transition: 'all 0.3s ease',
  },
  expandIcon: {
    fontSize: '0.9rem',
    color: '#3b82f6',
    transition: 'transform 0.3s ease',
  },
  doctorsList: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(280px, 1fr))',
    gap: '24px',
    marginTop: '24px',
  },
  doctorCard: {
    background: 'linear-gradient(135deg, #ffffff 0%, #f0f9ff 100%)',
    padding: '24px',
    borderRadius: '12px',
    border: '2px solid #dbeafe',
    transition: 'all 0.3s ease',
    cursor: 'pointer',
    boxShadow: '0 4px 15px rgba(59, 130, 246, 0.1)',
  },
  doctorCardHover: {
    boxShadow: '0 8px 25px rgba(59, 130, 246, 0.25)',
    borderColor: '#3b82f6',
    transform: 'translateY(-4px)',
  },
  doctorCardName: {
    fontSize: '1.2rem',
    fontWeight: '700',
    color: '#1e293b',
    marginBottom: '8px',
  },
  doctorCardInfo: {
    fontSize: '0.95rem',
    color: '#64748b',
    marginBottom: '6px',
    lineHeight: '1.5',
  },
  appointmentList: {
    listStyleType: 'none',
    padding: 0,
    margin: 0,
  },
  appointmentCard: {
    background: 'linear-gradient(135deg, #ffffff 0%, #f0f9ff 100%)',
    marginBottom: '20px',
    padding: '24px',
    borderRadius: '12px',
    border: '2px solid #dbeafe',
    transition: 'all 0.3s ease',
    boxShadow: '0 4px 15px rgba(59, 130, 246, 0.1)',
  },
  appointmentCardHover: {
    boxShadow: '0 8px 25px rgba(59, 130, 246, 0.25)',
    borderColor: '#3b82f6',
    transform: 'translateY(-3px)',
  },
  appointmentInfo: {
    marginBottom: '12px',
    fontSize: '1rem',
    color: '#475569',
    lineHeight: '1.6',
  },
  appointmentLabel: {
    fontWeight: '600',
    color: '#1e293b',
    display: 'inline-block',
    minWidth: '100px',
  },
  button: {
    background: 'linear-gradient(135deg, #3b82f6 0%, #1d4ed8 100%)',
    border: 'none',
    padding: '12px 24px',
    borderRadius: '10px',
    color: '#fff',
    cursor: 'pointer',
    fontWeight: '600',
    fontSize: '1rem',
    transition: 'all 0.3s ease',
    boxShadow: '0 4px 15px rgba(59, 130, 246, 0.4)',
    marginRight: '12px',
    letterSpacing: '0.3px',
  },
  buttonHover: {
    background: 'linear-gradient(135deg, #2563eb 0%, #1e40af 100%)',
    boxShadow: '0 6px 20px rgba(59, 130, 246, 0.6)',
    transform: 'translateY(-2px)',
  },
  cancelButton: {
    background: '#ef4444',
    border: 'none',
    padding: '12px 24px',
    borderRadius: '8px',
    color: '#fff',
    cursor: 'pointer',
    fontWeight: '600',
    fontSize: '1rem',
    transition: 'all 0.2s ease',
    boxShadow: '0 1px 3px rgba(239, 68, 68, 0.3)',
    letterSpacing: '0.3px',
  },
  cancelButtonHover: {
    background: '#dc2626',
    boxShadow: '0 2px 5px rgba(239, 68, 68, 0.4)',
  },
  input: {
    width: '100%',
    padding: '12px 16px',
    marginBottom: '18px',
    borderRadius: '10px',
    border: '2px solid #dbeafe',
    fontSize: '1rem',
    background: '#f0f9ff',
    transition: 'all 0.3s ease',
    outline: 'none',
    boxSizing: 'border-box',
    color: '#1e3a8a',
  },
  inputFocus: {
    border: '2px solid #3b82f6',
    background: '#ffffff',
    boxShadow: '0 0 0 4px rgba(59, 130, 246, 0.1)',
  },
  textarea: {
    width: '100%',
    padding: '12px 16px',
    marginBottom: '18px',
    borderRadius: '10px',
    border: '2px solid #dbeafe',
    fontSize: '1rem',
    background: '#f0f9ff',
    transition: 'all 0.3s ease',
    outline: 'none',
    boxSizing: 'border-box',
    color: '#1e3a8a',
    minHeight: '120px',
    resize: 'vertical',
    fontFamily: "'Inter', 'Segoe UI', -apple-system, BlinkMacSystemFont, sans-serif",
  },
  textareaFocus: {
    border: '2px solid #3b82f6',
    background: '#ffffff',
    boxShadow: '0 0 0 4px rgba(59, 130, 246, 0.1)',
  },
  select: {
    width: '100%',
    padding: '12px 16px',
    marginBottom: '18px',
    borderRadius: '8px',
    border: '2px solid #e2e8f0',
    fontSize: '1rem',
    background: '#f8fafc',
    transition: 'all 0.2s ease',
    outline: 'none',
    boxSizing: 'border-box',
    color: '#1e293b',
    cursor: 'pointer',
  },
  selectFocus: {
    border: '2px solid #2563eb',
    background: '#ffffff',
  },
  label: {
    fontWeight: '600',
    marginBottom: '8px',
    display: 'block',
    color: '#475569',
    fontSize: '0.95rem',
    letterSpacing: '0.2px',
  },
  formSection: {
    marginTop: '32px',
    padding: '28px',
    background: '#ffffff',
    borderRadius: '12px',
    border: '1px solid #e2e8f0',
  },
  formTitle: {
    fontSize: '1.3rem',
    fontWeight: '700',
    marginBottom: '20px',
    color: '#1e293b',
  },
  statusBadge: {
    display: 'inline-block',
    padding: '6px 16px',
    borderRadius: '20px',
    fontSize: '0.85rem',
    fontWeight: '600',
    marginLeft: '12px',
    letterSpacing: '0.3px',
  },
  statusPending: {
    background: '#fef3c7',
    color: '#92400e',
    border: '1px solid #fde68a',
  },
  statusConfirmed: {
    background: '#d1fae5',
    color: '#065f46',
    border: '1px solid #a7f3d0',
  },
  statusCompleted: {
    background: '#dbeafe',
    color: '#1e40af',
    border: '1px solid #bfdbfe',
  },
  statusCancelled: {
    background: '#fee2e2',
    color: '#991b1b',
    border: '1px solid #fecaca',
  },
  // Appointment Details (Expanded)
  appointmentDetails: {
    padding: '24px',
    background: 'linear-gradient(135deg, #f0f9ff 0%, #e0f2fe 100%)',
    borderTop: '2px solid #dbeafe',
    animation: 'slideDown 0.3s ease',
  },
  detailsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(250px, 1fr))',
    gap: '20px',
    marginBottom: '20px',
  },
  detailItem: {
    background: 'white',
    padding: '16px',
    borderRadius: '10px',
    border: '1px solid #dbeafe',
  },
  detailLabel: {
    fontSize: '0.85rem',
    fontWeight: '700',
    color: '#3b82f6',
    marginBottom: '8px',
    textTransform: 'uppercase',
    letterSpacing: '0.5px',
  },
  detailValue: {
    fontSize: '1rem',
    color: '#1e293b',
    fontWeight: '500',
  },
  doctorDetailsInfo: {
    marginTop: '4px',
  },
  doctorFullName: {
    fontSize: '1.1rem',
    fontWeight: '700',
    color: '#1e293b',
    marginBottom: '4px',
  },
  doctorEmail: {
    fontSize: '0.9rem',
    color: '#64748b',
  },
  appointmentId: {
    background: '#f0f9ff',
    padding: '4px 12px',
    borderRadius: '6px',
    fontFamily: 'monospace',
    fontSize: '0.95rem',
    color: '#1e40af',
    border: '1px solid #dbeafe',
  },
  
  // Notifications Section
  notificationSection: {
    marginTop: '20px',
    background: 'white',
    borderRadius: '10px',
    padding: '20px',
    border: '1px solid #dbeafe',
  },
  notificationTitle: {
    fontSize: '1rem',
    fontWeight: '700',
    color: '#3b82f6',
    marginBottom: '12px',
  },
  notificationList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
  },
  notificationItem: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '12px',
    background: '#f0f9ff',
    borderRadius: '8px',
    border: '1px solid #dbeafe',
  },
  notificationContent: {
    fontSize: '0.9rem',
    color: '#1e293b',
  },
  notificationMeta: {
    fontSize: '0.85rem',
  },
  notificationSeen: {
    color: '#10b981',
    fontWeight: '600',
  },
  notificationNew: {
    color: '#f59e0b',
    fontWeight: '600',
  },
  
  // Empty State
  emptyState: {
    textAlign: 'center',
    padding: '80px 24px',
    background: 'white',
    borderRadius: '16px',
    border: '2px dashed #dbeafe',
  },
  emptyStateIcon: {
    fontSize: '4rem',
    marginBottom: '20px',
    opacity: 0.5,
  },
  emptyStateText: {
    fontSize: '1.5rem',
    fontWeight: '700',
    color: '#64748b',
    marginBottom: '10px',
  },
  emptyStateSubtext: {
    fontSize: '1rem',
    color: '#94a3b8',
  },
  paymentSection: {
    marginTop: '20px',
    padding: '20px',
    background: 'linear-gradient(135deg, #dbeafe 0%, #bfdbfe 100%)',
    borderRadius: '12px',
    border: '2px solid #93c5fd',
  },
  paymentButton: {
    background: 'linear-gradient(135deg, #3b82f6 0%, #2563eb 100%)',
    border: 'none',
    padding: '12px 24px',
    borderRadius: '10px',
    color: '#fff',
    cursor: 'pointer',
    fontWeight: '600',
    fontSize: '1rem',
    transition: 'all 0.3s ease',
    boxShadow: '0 4px 15px rgba(59, 130, 246, 0.4)',
    letterSpacing: '0.3px',
  },
  paymentButtonHover: {
    background: 'linear-gradient(135deg, #2563eb 0%, #1d4ed8 100%)',
    boxShadow: '0 6px 20px rgba(59, 130, 246, 0.6)',
    transform: 'translateY(-2px)',
  },
  
  // Modal Styles
  modalOverlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    background: 'rgba(0, 0, 0, 0.7)',
    backdropFilter: 'blur(8px)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1000,
    padding: '20px',
    animation: 'fadeIn 0.2s ease',
  },
  modalContent: {
    background: 'white',
    borderRadius: '20px',
    padding: '40px',
    maxWidth: '600px',
    width: '100%',
    maxHeight: '90vh',
    overflowY: 'auto',
    boxShadow: '0 20px 60px rgba(0, 0, 0, 0.3)',
    animation: 'slideUp 0.3s ease',
    position: 'relative',
  },
  modalTitle: {
    fontSize: '2rem',
    fontWeight: '800',
    background: 'linear-gradient(135deg, #1e40af 0%, #3b82f6 100%)',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
    marginBottom: '30px',
    textAlign: 'center',
  },
  
  // Form Styles
  formGroup: {
    marginBottom: '24px',
  },
  formLabel: {
    display: 'block',
    fontSize: '0.95rem',
    fontWeight: '700',
    color: '#1e293b',
    marginBottom: '10px',
    letterSpacing: '0.3px',
  },
  formInput: {
    width: '100%',
    padding: '14px 16px',
    borderRadius: '10px',
    border: '2px solid #dbeafe',
    fontSize: '1rem',
    background: '#f0f9ff',
    transition: 'all 0.3s ease',
    outline: 'none',
    boxSizing: 'border-box',
    color: '#1e3a8a',
    fontFamily: "'Inter', 'Segoe UI', -apple-system, BlinkMacSystemFont, sans-serif",
  },
  formSelect: {
    width: '100%',
    padding: '14px 16px',
    borderRadius: '10px',
    border: '2px solid #dbeafe',
    fontSize: '1rem',
    background: '#f0f9ff',
    transition: 'all 0.3s ease',
    outline: 'none',
    boxSizing: 'border-box',
    color: '#1e3a8a',
    cursor: 'pointer',
    fontFamily: "'Inter', 'Segoe UI', -apple-system, BlinkMacSystemFont, sans-serif",
  },
  buttonGroup: {
    display: 'flex',
    gap: '12px',
    marginTop: '30px',
  },
  modalCancelButton: {
    flex: 1,
    padding: '14px 24px',
    borderRadius: '10px',
    border: '2px solid #e5e7eb',
    background: 'rgba(107, 114, 128, 0.1)',
    color: '#6b7280',
    fontSize: '1rem',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'all 0.3s ease',
  },
  submitButton: {
    flex: 2,
    padding: '14px 24px',
    borderRadius: '10px',
    border: 'none',
    background: 'linear-gradient(135deg, #10b981 0%, #059669 100%)',
    color: 'white',
    fontSize: '1rem',
    fontWeight: '700',
    cursor: 'pointer',
    transition: 'all 0.3s ease',
    boxShadow: '0 4px 15px rgba(16, 185, 129, 0.3)',
  },
};

// Add CSS animations
if (typeof document !== 'undefined') {
  const style = document.createElement('style');
  style.textContent = `
    @keyframes fadeIn {
      from { opacity: 0; }
      to { opacity: 1; }
    }
    @keyframes slideUp {
      from {
        opacity: 0;
        transform: translateY(30px);
      }
      to {
        opacity: 1;
        transform: translateY(0);
      }
    }
    @keyframes slideDown {
      from {
        opacity: 0;
        max-height: 0;
      }
      to {
        opacity: 1;
        max-height: 1000px;
      }
    }
  `;
  document.head.appendChild(style);
}

export default patientDashboardStyles;
